[package]
name = "graphviz-sys"
version = "0.1.0"
authors = ["Kenan Sulayman <kenan@sly.mn>"]
edition = "2018"

[[example]]
name = "example"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.51.1"
